name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # state managment
  flutter_bloc: ^8.1.5

  # comparing dart objects
  equatable: ^2.0.5

  # service locator
  get_it: ^7.7.0

  # dateFormat
  intl: ^0.19.0

  #Datebase
  floor: ^1.5.0

  # make API request
  retrofit: ^4.1.0

  # hooks
  flutter_hooks: ^0.20.5

  # cached image
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  retrofit_generator: '>=7.0.0 <8.0.0' 

flutter:
  uses-material-design: true
